### ISSUE TITLE
Server window closing the moment I open it.

### ISSUE THREAD

**Issue by Encephala** [MartB/RETC#9]
Hi,
In the usage section it says to open the server exe and leave it open. However, when I open the exe, it instantly closes again. Overwatch does not display any effects to my keyboard.
I do have a service called RETC running according to task manager.
The server.log file has the following:
[2017-06-14 16:17:10.537] [error] [SDKLoader::load] LoadLibraryA(RzChromaSDK64.dll) failed with code 126
[2017-06-14 16:17:10.559] [error] [LightingSDK::init] RazerPassthrough failed to load.

However, if I try to start the server again, it does not add any error messages.

I'm on x64, AMD Athlon x4 760k, AMD radeon 270 and 8GB ram on Windows 10.
I definitely have the SDK enabled within CUE, and the .dll files are in the overwatch folder.

Do you know what I can do to fix this issue?

**Comment by MartB** [comment]
Hey, if you installed the service correctly (i guess you did otherwise the service wouldnt show up) you dont need to launch the console window, maybe the instructions i have in the readme are a bit confusing.
That error is related to a different sdk i have implemented and its harmless in your case but it basically tells me overwatch connected to the retc server atleast.
Can you restart the service, launch overwatch and check the logfiles in C:\program files\RETC ?

**Comment by Encephala** [comment]
I restarted the service, but it still doesn't work.
I can't find an RETC folder anywhere in my program files.

**Comment by MartB** [comment]
reinstall it note down the part then check there.

**Comment by Encephala** [comment]
In my installation directory there is the server.log file, which has the lines above, and the retc-server-nssm.log file, which is empty. There are no other log files.

**Comment by MartB** [comment]
only the lines above ?
If thats the case there should not be any issue :octocat: 
Which version of cue are you using ?
Can you start your cue for a quick test ?
